### ISSUE TITLE
can't find pandoc-citeproc.exe in the latest pandoc 

### ISSUE THREAD

**Issue by sean-xia** [annProg/PanBook#36]
As the title describedl I can't find the pandoc-citeproc.exe in the latest version of pandoc(2.13), how can i solve this problem?

**Comment by annProg** [comment]
since version 2.11 no external pandoc-citeproc needed

> Add --citeproc (-C) option to trigger built-in citation processing. It is no longer necessary to use the external pandoc-citeproc filter. --citeproc behaves like a filter and can be positioned relative to other filters as they appear on the command line.

https://github.com/jgm/pandoc/releases/tag/2.11
